### ISSUE TITLE
As a developer, I need a dev environment

### ISSUE THREAD

**Issue by heyozramos** [heyozramos/posenet-cursor#1]
## Scope
- [x] I can type `npm start` to launch a local dev server
- [x] I can type `npm run build` to build the project
- [x] I can type `npm run deploy` to deploy the site to my configured server

## Tasks
- [x] Setup `.gitignore`, `README.md`, and `package.json`
- [x] Create a simple landing page with live reload
- [x] Include TensorFlow/PoseNet

**Comment by heyozramos** [comment]
Finished! The demo will be available at https://posenet-cursor.firebaseapp.com, although there's not much there yet
