### ISSUE TITLE
As a dev, I need to train a model to learn head pose from posenet keypoints

### ISSUE THREAD

**Issue by heyozramos** [heyozramos/posenet-cursor#2]
Let's use [Babylon.js](https://www.babylonjs.com/) as our canvas to feed into PoseNet. Inside the scene, we'll add a photorealistic head to use as synthetic data for training a small NN to position a cursor based on the PoseNet pose information.

## Scope
- [ ] I have a workflow for retraining a model from PoseNet data
- [ ] I can run `npm run train` to train or retrain a model
- [ ] I can use the model to position a cursor

## Tasks
- [x] Setup babylon
- [x] Setup PoseNet
- [x] Add buttons for starting and training
- [x] Reposition head on each training step
- [ ] Store each training sample
- [ ] Train the model
